### ISSUE TITLE
Calling one sub command from another doesn't return to caller

### ISSUE THREAD

**Issue by dsl101** [tomerfiliba/plumbum#171]
First of all, what a fab library - there's no way I'd have got so far so quickly without it. But of course, now I've seen the potential, I can't stop building more features into our app. I've created several stand-alone subcommands, but now I would like a higher-level subcommand which basically generates a list of things to do, and then calls other subcommands to do the work.

However on the first internal call to a subcommand, the whole thing terminates rather than returning to the first subcommand. Is there a way to allow control to return when a subcommand is called internally? Here's a minimal test which never outputs `Back in sub1`:

	#!/usr/bin/env python3
	# -*- coding: utf-8 -*-

	from plumbum import cli

	class subtest(cli.Application):
		VERSION = "1.0"

		def main(self, *args):
			if args:
				print("Unknown command %r" % (args[0],))
				return 1
			if not self.nested_command:
				print("No command given")
				return 2

	@subtest.subcommand("sub1")
	class sub1(cli.Application):
		"""Test calling other class methods"""

		def main(self, param):
			print("sub1 parent: %s" % self.parent)
			print("sub1 param: %s" % param)
			sub2.run(['sub1', "%s-called" % param])
			print("Back in sub1")

	@subtest.subcommand("sub2")
	class sub2(cli.Application):
		"""Test called from other class methods"""

		def main(self, param):
			print("sub2 parent: %s" % self.parent)
			print("sub2 param: %s" % param)

	if __name__ == '__main__':
		subtest.run()

On a related note, if I call `subtest sub1 somedata`, this is what I see as output:

	sub1 parent: <__main__.subtest object at 0x7fc14e0da350>
	sub1 param: somedata
	sub2 parent: None
	sub2 param: somedata-called

I was half expecting sub2 parent to be sub1, but it always seems to be 'None'. Is there a way for a subcommand to know _which_ other subcommand called it?

I'm using Plumbum 1.4.2, and pip3 says it's the latest version.

Many thanks,

David.

**Comment by tomerfiliba** [comment]
`App.run` accepts a second parameter, `exit`, which can be True or False. try passing false. also -- try using `App.invoke` instead of `run`. see https://github.com/tomerfiliba/plumbum/blob/master/plumbum/cli/application.py#L382

about the second issue, the parent is set by `run` of the parent command. see https://github.com/tomerfiliba/plumbum/blob/master/plumbum/cli/application.py#L367

this means that if you call run explicitly, you don't have a parent unless you have a `nested_command`, which is set by https://github.com/tomerfiliba/plumbum/blob/master/plumbum/cli/application.py#L199

the subcommands were not designed for "stacking", they're meant to model `git` or other such tools with command modularity. one command relaying to another was not an intended use case (although patches are happily accepted -- so long as they come with unittests and don't break anything else)

**Comment by dsl101** [comment]
Hey - thanks for the pointer to the second parameter to `run()` - that did exactly what I wanted. I was a little confused by the comment about `invoke()` and return values though - it implies it gives direct access to the return value where `run()` doesn't, but if I print the result of calling `run()`, I see something like this:

    run sub2:  (<__main__.sub2 object at 0x7fe6e3320750>, 'finished')

So it looks like I can get the return value without it being converted to an integer anyway. Or did I misunderstand what `invoke()` offers? I did try `invoke()`, but I just can't figure out the correct syntax - probably just my inexperience with Python to be honest. I tried `self.invoke()` and `cli.Application.invoke()`, but I just get `AttributeError: type object 'Application' has no attribute 'invoke'` or similar.

Finally, if I just include `sub2.parent = self` in `sub1`, everything looks as it should once in `sub2`, so hopefully no patches required! Many thanks again for this fab library.
