### ISSUE TITLE
TEE modifier does not work for python3

### ISSUE THREAD

**Issue by gaschreiber** [tomerfiliba/plumbum#185]
plumbum.commands.modifiers.TEE does not work for python3. 
sys.stdout expects str type, but is given bytes.

When you change 
plumbum.commands.modifiers.py:168
to
`tee_to[fd].buffer.write(data)`
it fixes the issue, but I'm not sure if this is clean, because of buffering.

**Comment by Semoar** [comment]
For Python 3 it would be good. A problem is Python2, since back then there was no buffer.write(). Probably a conversion to string using `tee_to[fd].write(data.decode('utf-8'))` would be better. 

I found out I also have to convert the return values from byte to str the same way.

Only thing I am not sure, if there isn't a better way than hardcoding utf-8...
