### ISSUE TITLE
Single definition for both API facade and CLI interface

### ISSUE THREAD

**Issue by KOLANICH** [tomerfiliba/plumbum#312]
For now attribbutes are defined as fields of the class. This is not idiomatic. It could be nice to find a way to define them as field of prototype of main.

```python
class Opts(cli.Options):
	class first(cli.Group):
		"""The first group description"""
		NAME="First group"
		a=cli.Flag("-a", help = "a")
                b=cli.Flag("-b", help = "b")
	
	c = cli.Flag("-c", help = "c")

class MyApp(cli.Application):
	def main(self, *args, **opts:Opts):
		print(opts.a, opts.b, opts.c)
```

**Comment by henryiii** [comment]
The `main` arguments are currently for positional arguments, and annotations are used to provide validators in Python 3 (and a workaround is available in Python 2). The problem here is that this breaks up the structure in a non-clear way just to make `main` slightly more like a standard function (But it's still a class member), and hides the attributes. I think it is much clearer to think of optional arguments as class members, and there's also the functional form of switches which makes much more sense if the functions have access to the rest of the arguments.

**Comment by KOLANICH** [comment]
>The problem here is that this breaks up the structure in a non-clear way

Will the way be more clear if we made Opts a subclass of MyApp?

Another way to implement it is to generate __call__(), with options and args in prototype.

**Comment by henryiii** [comment]
Is `.invoke` what you want? You don't want use `run` or `__call__`, since those exit your app with the correct error codes, where as `.invoke` works from Plumbum. And it does `*args` for positionals and `**kargs` for options.

**Comment by henryiii** [comment]
Since I think this is the way invoke works, I'll close this, reopen if I'm wrong.
