### ISSUE TITLE
Changing working directory on several processes in parallel

### ISSUE THREAD

**Issue by yonilx** [tomerfiliba/plumbum#320]
I'm trying to use plumbum and the :
```
with local.cwd(dir_path):
    code...
```

command in order to change the working directory on several processes in parallel.
However, I'm getting some crashes and I suspect the culprit of this is plumbum as putting a lock on this part of the code seemed to solve the problem.

Is there another way to change directories which doesn't interfere with other processes ?

**Comment by henryiii** [comment]
Plumbun uses `os.chdir` [behind the scenes](https://github.com/tomerfiliba/plumbum/blob/dc7642733c963598af7807c95a3c9e1787507557/plumbum/path/local.py#L324-L358). It is possible to use full paths (`plumbum.path` makes this easy, you can just do `my_loc_dir / filename`)?

**Comment by henryiii** [comment]
The `.popen` method also takes an explicit `cwd` that defaults to `self.cwd`, you might be able to directly change that. It could be wrapped into a modifier.

The main problem is that Plumbum is keeping the local directory in sync with Python. This is usually what you want, since some processes do not consult Plumbum (and even in your case, you are not using the return value of `local.cwd` so you are using the global python value).

Question, @yonilx: Does the code crash because you are in the wrong directory or because you are changing the directory at the same time? The first is easier to fix. Do you use Plumbum commands inside the with statement or are you using non-plumbum commands that use the `os.curdir` value?

**Comment by yonilx** [comment]
It turns out the problem is on my part where the library I was using used threads when I thought they used processes. 
Threads share the working directory (set by `os.chdir()` as you stated) so all my threads interfered with each other, causing my code to crash.

The use-case within the `with` statement looks something like:
```
with local.cwd(dir_path):
    prog = local[prog_abs_path]
    prog.run([args])
```
What I would like to do is to set the working directory for the specific prog.run call, the `with` statement is just boilerplate code for me as I'm only using it for the run() call, so in case `popen` really does seem to fit, thanks for the suggestion !
