### ISSUE TITLE
Root mode context manager?

### ISSUE THREAD

**Issue by harlowja** [tomerfiliba/plumbum#9]
It might be useful to say do the following:

```
ls = local['ls'] (or use SshMachine here...)
with Root(ls) as root_ls:
    root_ls.run()
```

This way people can run as other users in a pythonic way (root show as an example here). Similarly the same would be neat with ssh/remote shells. Sometimes u just need to run a single command as another user (ie `apt-get install`) and u don't want the rest of the commands ran as that user... Thoughts?

**Comment by AndydeCleyre** [comment]
I understand why this issue was rejected as applied to running arbitrary commands, but I'll note that I arrived here looking for a way to perform a few `local.path` operations with `sudo`, such as `delete` and `symlink`. AFAIK the current way to do this is to avoid those functions and instead do 

```python
local['sudo'](local['rm', '-r'][local.path('somepath')])
local['sudo'](local['ln', '-s']['existspath', 'newpath'])
```

I can imagine a more natural feel with something like

```python
with local.path.as_root(): # or local.path.as_user('root'):
    local.path('somepath').delete()
    local.path('existspath').symlink('newpath')
```

or even

```python
local.path('somepath').delete(sudo=True) # or .delete(user='root')
local.path('existspath').symlink('newpath', sudo=True) # or .symlink('newpath', user='root')
```
